symbolicName=io.openliberty.enterpriseBeansHome-4.0
visibility=public
-include=~${workspace}/cnf/resources/bnd/feature.props
IBM-App-ForceRestart=install, uninstall
kind=beta
WLP-AlsoKnownAs=ejbHome-4.0
WLP-Activation-Type=parallel
edition=base
-features=com.ibm.websphere.appserver.eeCompatible-9.0,io.openliberty.enterpriseBeansLite-4.0,com.ibm.websphere.appserver.transaction-2.0
-bundles=com.ibm.ws.ejbcontainer.ejb2x
Subsystem-Name=Jakarta Enterprise Beans 4.0 Home Interfaces
IBM-ShortName=enterpriseBeansHome-4.0
