symbolicName=com.ibm.websphere.appserver.certificateCreator-1.0
visibility=private
-include=~${workspace}/cnf/resources/bnd/feature.props
IBM-App-ForceRestart=install, uninstall
WLP-DisableAllFeatures-OnConflict=false
kind=ga
singleton=true
edition=core
-bundles=com.ibm.ws.crypto.certificate.creator.selfsigned
Subsystem-Version=1.0.0
