symbolicName=com.ibm.websphere.appserver.injection-1.0
-include=~${workspace}/cnf/resources/bnd/feature.props
WLP-DisableAllFeatures-OnConflict=false
singleton=true
kind=ga
WLP-Activation-Type=parallel
edition=core
-features=com.ibm.websphere.appserver.containerServices-1.0,com.ibm.websphere.appserver.anno-1.0
-bundles=com.ibm.ws.injection
IBM-Process-Types=client, server
