symbolicName=io.openliberty.authFilter1.0.internal.ee-6.0
visibility=private
-include=~${workspace}/cnf/resources/bnd/feature.props
WLP-DisableAllFeatures-OnConflict=false
singleton=true
kind=ga
WLP-Activation-Type=parallel
edition=core
-features=io.openliberty.servlet.api-3.0;ibm.tolerates:="3.1,4.0"
-bundles=com.ibm.ws.security.authentication.filter
