symbolicName=io.openliberty.spnego1.0.internal.ee-6.0
visibility=private
-include=~${workspace}/cnf/resources/bnd/feature.props
WLP-DisableAllFeatures-OnConflict=false
singleton=true
kind=ga
edition=core
-features=com.ibm.websphere.appserver.appSecurity-2.0;ibm.tolerates:="3.0",com.ibm.websphere.appserver.servlet-3.0;ibm.tolerates:="3.1,4.0"
-bundles=com.ibm.ws.security.spnego
